// Generated by https://quicktype.io

export interface Team {
  scope: string;
  members: any[];
  answersScore: number;
  bonusScore: number;
  hints: number;
  correctAnswers: number;
  incorrectAnswers: number;
  totalAnswers: number;
  name: string;
  color: string;
  isFinished: boolean;
  odometer: number;
  id: string;
  totalScore: number;
  startTime: number;
  finishTime: number;
}
